#!/bin/sh

python manage.py shell << EOF
import os

from helios_auth.models import User

User.objects.get_or_create(user_type="password", user_id="admin", name=os.environ["ADMIN_NAME"], info={"password": os.environ["ADMIN_PASSWORD"]}, admin_p=True)
EOF
